[build]
beforeDevCommand = "trunk serve"
beforeBuildCommand = "trunk build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = true

[package]
productName = "minimal_tauri_yew_bevy"
version = "0.0.0"

[tauri.allowlist]
all = false

[tauri.allowlist.shell]
all = false
open = true

[tauri.bundle]
active = true
targets = "all"
identifier = "test.tauri.dev"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

[tauri.security]

[[tauri.windows]]
label = "main"
title = "minimal_tauri_yew_bevy"
fullscreen = false
resizable = true
center = true
width = 1_400
height = 900
visible = false  # hide main window initially to just show splash
url = "index.html"

[[tauri.windows]]
label = "splashscreen"
width = 500
height = 300
decorations = false
center = true
transparent = true
url = "splashscreen.html"
